language: java
jdk:
  - oraclejdk8
before_install: mvn clean
install: mvn install -DskipTests=true
script: echo "test skip"
deploy:
  provider: releases
  api_key: authentication_token
  file: target/OneDriveAPI*.jar
  on:
    repo: gingkojp/aipo
