language: java
jdk:
  - oraclejdk8
before_install: mvn clean
install: mvn install -DskipTests=true
script: echo "install OneDriveAPI"
deploy:
  provider: releases
  api_key: authentication_token
  file: target/OneDriveAPI*.jar
  skip_cleanup: true
  on:
    tag: true
